trigger:
  - dev

variables:
  - group: "common"
  - name: IMAGE_NAME
    value: pomotracker

pool: mycomputeragent


stages:
  - stage: Build
    displayName: Build docker images and push to docker hub
    jobs:
      - job: Build
        steps:

          - task: Docker@2
            displayName: Docker login
            inputs:
              containerRegistry: '$(CONTAINER_REGISTRY)'
              command: 'login'

          - task: Docker@2
            displayName: Docker build
            inputs:
              containerRegistry: '$(CONTAINER_REGISTRY)'
              repository: '$(DOCKER_REPO)/$(IMAGE_NAME)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(DOCKER_TAG)
                latest

          - task: Docker@2
            displayName: Docker push
            inputs:
              containerRegistry: '$(CONTAINER_REGISTRY)'
              repository: '$(DOCKER_REPO)/$(IMAGE_NAME)'
              command: 'push'
              tags: |
                $(TAG)
                latest

  - stage: Deploy
    displayName: Deploy to VM via ssh
    jobs:
      - job: Deploy
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'ssh-service-connection'
              runOptions: 'commands'
              commands: |
                bash /home/azuredevops/rm_img_docker.sh viodid/calat33 latest calart.org
                docker pull viodid/calat33:latest
                docker run -d -p 8888:8888 --name calart.org viodid/calat33:latest

