trigger:
  - main

variables:
  - group: "common"
  - name: IMAGE_NAME
    value: pomotracker

pool: mycomputeragent


stages:
  - stage: Build
    displayName: Build docker images and push to docker hub
    jobs:
      - job: Build
        steps:
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'docker-registry'
              dockerComposeFile: './docker-compose.yml'
              action: 'Build services'

          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'docker-registry'
              dockerComposeFile: './docker-compose.yml'
              action: 'Push services'

  # - stage: Deploy
  #   displayName: Deploy to VM via ssh
  #   jobs:
  #     - job: Deploy
  #       steps:
  #         - task: SSH@0
  #           inputs:
  #             sshEndpoint: 'ssh-service-connection'
  #             runOptions: 'commands'
  #             commands: |
  #               bash /home/azuredevops/rm_img_docker.sh viodid/calat33 latest calart.org
  #               docker pull viodid/calat33:latest
  #               docker run -d -p 8888:8888 --name calart.org viodid/calat33:latest