trigger:
  - main

variables:
  - group: "common"
  - name: FIRST_IMAGE_NAME
    value: pomotracker
  - name: SECOND_IMAGE_NAME
    value: pomotracker-nginx

pool: mycomputeragent


stages:
  - stage: Build
    displayName: Build docker images and push to docker hub
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-registry'
              repository: '$(DOCKER_REPO)/$(FIRST_IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                $(TAG)

          - task: Docker@2
            inputs:
              containerRegistry: 'docker-registry'
              repository: '$(DOCKER_REPO)/$(SECOND_IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: '**/config/nginx/Dockerfile'
              tags: |
                $(Build.BuildId)
                $(TAG)

  - stage: Deploy
    displayName: Deploy to VM via ssh
    jobs:
      - job: Deploy
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'ssh-service-connection'
              runOptions: 'commands'
              commands: |
                bash /home/azuredevops/rm_img_docker.sh '$(DOCKER_REPO)/$(FIRST_IMAGE_NAME)' latest pomotracker.app
                docker pull '$(DOCKER_REPO)/$(FIRST_IMAGE_NAME):latest'