version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - pomotracker-network

  app:
    build: .
    env_file:
      - PomoTracker/.env
    ports:
      - 80:8000
    networks:
      - pomotracker-network
    depends_on:
      - redis

networks:
  pomotracker-network:
    driver: bridge