version: '3.8'

services:
  redis:
    image: redis:7.2.1
    expose:
      - 6379
    networks:
      - pomotracker-network

  postgres:
    build: ./config/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpostgres1234
      - POSTGRES_DB=pomotracker
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - pomotracker-network

  app:
    build: .
    command: gunicorn PomoTracker.wsgi:application --bind 0.0.0.0:80 --timeout 600 --workers 3
    env_file:
      - ./PomoTracker/.dev.env
    volumes:
      - static_volume:/home/app/pomotracker/staticfiles
    expose:
      - 80
    networks:
      - pomotracker-network
    depends_on:
      - redis
      - postgres

  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/pomotracker/staticfiles
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pomotracker-network

networks:
  pomotracker-network:
    driver: bridge

volumes:
  static_volume:
  postgres_data:
